from __future__ import annotations

from dataclasses import dataclass, field
from openai import OpenAI

from easp.models import Response


class LlmExplanationError(RuntimeError):
    """Raised when the LLM explanation request cannot be completed."""


@dataclass(frozen=True)
class AggregateGroup:
    label: str
    atoms: list[str]


@dataclass(frozen=True)
class AggregateDetail:
    rule: str
    key: str
    truth_message: str
    groups: list[AggregateGroup] = field(default_factory=list)
    error: str = ""


@dataclass(frozen=True)
class ExplanationContext:
    program: str
    page: str
    answer_sets: list[str]
    selected_answer_set: int
    chain: list[str]
    responses: list[Response]
    aggregate_details: list[AggregateDetail] = field(default_factory=list)


class OpenRouterClient:
    def __init__(
        self,
        api_key: str,
        *,
        app_title: str = "E-ASP",
        site_url: str | None = None,
        timeout_seconds: int = 45,
    ) -> None:
        self.api_key = api_key
        self.app_title = app_title
        self.site_url = site_url
        self.timeout_seconds = timeout_seconds

    def explain(self, context: ExplanationContext, model, temperature: float = 0.7, language: str = "English", technical_explanation_mode: bool = True) -> str | None:
        messages = [
            {
                "role": "system",
                "content": (
                    f"You explain Answer Set Programming debugging results in clear {language} (or in English if you don't know this language)."
                    "Use only the supplied context. If something is not shown, say that it is not visible "
                    "from the generated data. Prefer a concise discursive explanation over a bullet list."
                ),
            },
            {
                "role": "user",
                "content": build_discursive_prompt(context, language, technical_explanation_mode),
            },
        ]
        client = OpenAI(base_url="https://openrouter.ai/api/v1", api_key=self.api_key)
        chat_completion = client.chat.completions.create(model=model, messages=messages, temperature= temperature)
        return chat_completion.choices[0].message.content

def build_discursive_prompt(context: ExplanationContext, language: str, technical_explanation_mode: bool) -> str:
    if technical_explanation_mode:
        additional_instruction = (
            "Assume the user knows the ASP program "
            "but wants to understand this result."
        )
    else:
        additional_instruction = (
            "Assume the user does not know the details of the ASP program. "
            "Explain the outcome to a domain professional. "
            "Describe only the real-world reasons behind the decision, "
            "without exposing its ASP representation."
        )
    sections = [
        f"Explain the generated E-ASP result in {language} (or in English if you don't know this language).",
        "",
        f"Current page: {context.page}",
        _program_section(context.program),
        _answer_sets_section(context.answer_sets, context.selected_answer_set),
        _chain_section(context.chain),
        _responses_section(context.responses),
        _aggregate_details_section(context.aggregate_details),
        "",
        f"{additional_instruction}",
        "",
        "Write a clear explanation for such a user."
    ]
    return "\n".join(section for section in sections if section)


def _program_section(program: str) -> str:
    program = program.strip()
    if not program:
        return "Program: not available."
    return "Program:\n```asp\n" + program + "\n```"


def _answer_sets_section(answer_sets: list[str], selected_answer_set: int) -> str:
    if not answer_sets:
        return "Answer sets: none available. Program is UNSATISFIABLE."

    lines = ["Answer sets:"]
    for index, answer_set in enumerate(answer_sets):
        marker = "selected" if index == selected_answer_set else "available"
        lines.append(f"- {index + 1} ({marker}): {answer_set or '{}'}")
    return "\n".join(lines)


def _chain_section(chain: list[str]) -> str:
    if not chain:
        return ""
    return "Explanation chain: " + " -> ".join(chain)


def _responses_section(responses: list[Response]) -> str:
    if not responses:
        return ""

    lines = ["Generated explanations:"]
    for response in responses:
        lines.append(f"- {_response_type_name(response.type)}: {response.rule}")
    return "\n".join(lines)


def _aggregate_details_section(details: list[AggregateDetail]) -> str:
    if not details:
        return ""

    lines = ["Aggregate expansions generated by the debugger:"]
    for index, detail in enumerate(details, start=1):
        key = _clean_piece(detail.key) or "global aggregate"
        truth_message = _clean_piece(detail.truth_message) or "truth value not available"
        lines.append(f"{index}. Rule: {detail.rule}")
        lines.append(f"   Aggregate instance: {key}")
        lines.append(f"   Debugger evaluation: {truth_message}")

        if detail.error:
            lines.append(f"   Expansion error: {detail.error}")
            continue

        if not detail.groups:
            continue

        lines.append("   Expanded groups:")
        for group in detail.groups:
            label = _clean_piece(group.label) or "group"
            atoms = [_clean_piece(atom) for atom in group.atoms]
            visible_atoms = [atom for atom in atoms if atom]
            atom_text = ", ".join(visible_atoms) if visible_atoms else "no atoms"
            lines.append(f"   - {label}: {atom_text}")
    return "\n".join(lines)


def _response_type_name(type_: int) -> str:
    names = {
        0: "rule",
        1: "fact",
        2: "literal",
        3: "aggregate",
    }
    return names.get(type_, "item")


def _clean_piece(value: str) -> str:
    """Trim whitespace and leading/trailing commas from debugger output."""
    return value.strip().strip(",").strip()
